---
title: "An Introduction to the R Ecosystem"
subtitle: "Or, the R Introduction You Wish You'd Gotten in Class"
author: "Andrew Bates"
date: "10/22/2018"
output: 
  ioslides_presentation:
    logo: logo.jpeg
---

## What This Workshop Is Not

> - An introduction to R you would get in a class:
> - This is a list of the basic R data types...
> - This is how to create a vector ...
> - This is how to create a matrix ...
> - ...


## What This Workshop Is 

> - A simple data analysis walkthrough using:
> - R - the R language itself
> - RStudio - an IDE for the R language
> - R Markdown - a tool for generating documents that mix text with code


## Why?

>  - Being able to create a vector doesn't mean you can make a plot
>  - Being able to create a matrix doesn't mean you can fit a model

> - This workshop is more practical because
>     - You should to be able to take what you learn here and apply it to your own data
>     - You need to write up your analysis for it to be useful
>     - Using R with RStudio and R Markdown makes this seamless


## Setup

> - Make sure you have R and RStudio
> - Start a new RStudio project
>     - A way to keep your work organized
> - Go to my GitHub repository that has the files we will need:
>     - [https://github.com/asbates/ssa_r_workshops](https://github.com/asbates/ssa_r_workshops) 
> - Download the data in `fall_18/data/candy-data.csv`
> - Download the R Markdown file `fall_18/r-intro/candy-showdown.Rmd`
> - Save both files in your RStudio project


## Let's Get Started!


